<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE empleados [
    <!ELEMENT empleados (empleado*)>
        <!ATTLIST empleados total CDATA #REQUIRED>
    <!ELEMENT empleado (nombre, apellidos)>
        <!ATTLIST empleado id ID #REQUIRED>
        <!ATTLIST empleado seccion (desarrollo | sistemas) "sistemas">
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellidos (#PCDATA)>
]>

<empleados total="2">
    <empleado id="JDU" seccion="sistemas">
        <nombre>Jesulin</nombre>
        <apellidos>De Ubrique</apellidos>
    </empleado>
    <empleado id="MK" seccion="desarrollo">
        <nombre>Michael</nombre>
        <apellidos>Knight</apellidos>
    </empleado>
</empleados>